global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fcg-users-api"
    static_configs:
      - targets: ["users-api:8080"]
    metrics_path: /metrics

  - job_name: "fcg-catalog-api"
    static_configs:
      - targets: ["catalog-api:8080"]
    metrics_path: /metrics

  - job_name: "fcg-payments-api"
    static_configs:
      - targets: ["payments-api:8080"]
    metrics_path: /metrics

  - job_name: "fcg-notifications-api"
    static_configs:
      - targets: ["notifications-api:8080"]
    metrics_path: /metrics

  - job_name: "fcg-kong"
    static_configs:
      - targets: ["kong:8001"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
