apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "fcg-users-api"
  Jwt__Audience: "fcg-platform"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Username: "guest"
  Redis__ConnectionString: "redis-service:6379"
  MongoDB__ConnectionString: "mongodb://fcg_app:fcg_app_dev@mongodb-service:27017"
  MongoDB__DatabaseName: "fcg_reviews"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: fcg-catalog-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
          env:
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: Jwt__Secret
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: ConnectionStrings__Postgres
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: RABBITMQ_PASSWORD
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
  namespace: fcg
spec:
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-nodeport
  namespace: fcg
spec:
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
  type: NodePort
